# Numpy Exercises

In [1]:
import numpy as np

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?

In [3]:
negative_numbers = a[a < 0]

In [4]:
print(negative_numbers)

[-2 -1 -6 -7]


In [5]:
len(negative_numbers)

4

2. How many positive numbers are there?

In [6]:
positive_numbers = a[a > 0]
print(positive_numbers)
len(positive_numbers)

[ 4 10 12 23  3]


5

3. How many even positive numbers are there?

In [7]:
positive_numbers = a > 0

positives = a[positive_numbers]

even_numbers = positives % 2 == 0

positive_even_numbers = positives[even_numbers]

print(positive_even_numbers)
len(positive_even_numbers)

[ 4 10 12]


3

4. If you were to add 3 to each data point, how many positive numbers would there be?

In [8]:
a += 3
my_array = a[a > 0]
print(my_array)
len(my_array)

[ 7 13 15 26  1  2  3  3  3  6]


10

5. If you squared each number, what would the new mean and standard deviation be?