# Numpy Exercises

In [1]:
import numpy as np

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?

In [3]:
negative_numbers = a[a < 0]

In [4]:
print(negative_numbers)

[-2 -1 -6 -7]


In [5]:
len(negative_numbers)

4

2. How many positive numbers are there?

In [6]:
positive_numbers = a[a > 0]
print(positive_numbers)
len(positive_numbers)

[ 4 10 12 23  3]


5

3. How many even positive numbers are there?

In [7]:
positive_numbers = a > 0

positives = a[positive_numbers]

even_numbers = positives % 2 == 0

positive_even_numbers = positives[even_numbers]

print(positive_even_numbers)
len(positive_even_numbers)

[ 4 10 12]


3

4. If you were to add 3 to each data point, how many positive numbers would there be?

In [24]:
add_three = a + 3
add_three = a[a > 0]
print(add_three)
len(add_three)

[ 1  2  3  4  5  6  7  8  9 10]


10

5. If you squared each number, what would the new mean and standard deviation be?

In [9]:
a ** 2

array([ 49, 169, 225, 676,   1,   4,   9,   9,   9,   9,  36,  16])

In [10]:
%%timeit
[a ** 2 for a in range(1, 1_000_000)]

246 ms ± 1.38 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [11]:
mean = a.mean()
print(a.mean())
centered = a - mean
print(centered)

6.0
[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


7. Calculate the z-score for each data point. Recall that the z-score is given by:

In [12]:
import pandas as pd
import numpy as np
import scipy.stats as stats

stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

## 8. Life w/o numpy to life with numpy

In [13]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

a_array = np.array(a)


In [14]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

sum_of_a = a_array.sum()
print(sum_of_a)

55


In [15]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_a = a_array.min()
print(min_of_a)

1


In [16]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

max_of_a = a_array.max()
print(max_of_a)

10


In [17]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

mean_of_a = a_array.mean()
print(mean_of_a)

5.5


In [18]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

product_of_a = np.prod(a_array)
print(product_of_a)

3628800


In [19]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

squares_of_a = np.square(a_array)
print(squares_of_a)

[  1   4   9  16  25  36  49  64  81 100]


In [20]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

odds_in_a = a_array % 2 == 1
print(odds_in_a)

[ True False  True False  True False  True False  True False]


In [21]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

evens_in_a = a_array % 2 == 0
print(evens_in_a)

[False  True False  True False  True False  True False  True]


In [22]:
a = np.array(a)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
matrix = np.array
([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10]])
matrix

<function numpy.array>